name = "rootfleet-waitlist"
compatibility_date = "2025-12-23"

pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "rootfleet_waitlist"
database_id = "53ed2dfa-2608-4493-b9bd-f73a9a402acd"
