name = "rootfleet-waitlist"
compatibility_date = "2025-12-23"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "rootfleet_waitlist"
database_id = "0f85850c-0aaf-40f4-821a-061d3489968f"
