name = "waitlist-email-consumer"
main = "src/index.js"
compatibility_date = "2025-12-31"

[triggers]
crons = ["*/1 * * * *"] # every minute backstop

[vars]
DRAIN_BATCH_SIZE = "10"
RESEND_FROM = "Rootfleet <noreply@rootfleet.com>"

[[d1_databases]]
binding = "DB"
database_name = "rootfleet_waitlist"
database_id = "0f85850c-0aaf-40f4-821a-061d3489968f"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

